### ISSUE TITLE
Screenshots in the docs need to be updated

### ISSUE THREAD

**Issue by aosolis** [OfficeDev/microsoft-teams-app-quickstarts#10]
The instructions in the VS Code extension details don't match the actual UX (at least not on my instance?)
Compare the options in the left bar vs the one in the screenshots.

![image](https://user-images.githubusercontent.com/767208/87097779-cc317700-c1fa-11ea-8085-dc63f7e47d15.png)

**Comment by asnow003** [comment]
Created internal bug 
Bug 1035873: [VSC] Screenshots in readme need to be updated
