### ISSUE TITLE
Links are hard to read (low contrast ratio)

### ISSUE THREAD

**Issue by aosolis** [OfficeDev/microsoft-teams-app-quickstarts#11]
The links in the screenshot are hard to read. 
The contrast ratio is roughly 2.6:1. (I think the recommended ratio is at least 4.5:1 -- https://webaim.org/resources/contrastchecker/)

![image](https://user-images.githubusercontent.com/767208/87097974-28949680-c1fb-11ea-93d9-039e88c844a3.png)

**Comment by asnow003** [comment]
Thanks created another bug for this...we got a new color from design but guess it needs a little more tweaking

**Comment by asnow003** [comment]
Bug 1035870: [VSC] Link colors contrast ratio - can't see links
