### ISSUE TITLE
Bot management page hanging in loading page

### ISSUE THREAD

**Issue by SLdragon** [OfficeDev/microsoft-teams-app-quickstarts#12]
Hi, team, I try to create a bot project, and the bot management page is hanging in loading page as below:

![Capture](https://user-images.githubusercontent.com/5545529/87497443-23669a00-c688-11ea-934a-6ba36f75350b.PNG)

Any idea about how to solve the problem?

**Comment by JanaAbhijit** [comment]
Yes, even the same problem in Microsoft Team, if we open the **Manifest Editor** - **Bot Management** from **App Studio** 
![image](https://user-images.githubusercontent.com/12181773/88786385-1382a600-d1b0-11ea-8d71-6b90a2a21b8d.png)

**Comment by sebastianzolg** [comment]
Same here!

**Comment by asnow003** [comment]
This bug should be fixed now due to a token not refreshing when its expired.
