### ISSUE TITLE
Env parameterization doesn't work consistently

### ISSUE THREAD

**Issue by sschutten** [OfficeDev/microsoft-teams-app-quickstarts#15]
Some environment parameters are not replaced in the manifest.json. I have created a new app package from scratch, which then created an .env file with the following contents (the ids are fake):
```
appid=e0b47b6f-6268-4a1a-9664-cd5e1e7fdf82
version=1.0.0
appname=Test
fullappname=Test
botId0=1fe9918a-fe80-4f19-9507-4053200f73c4
```

After changing the manifest.json and saving, the manifest looks like this (simplified):

```json
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.schema.json",
    "manifestVersion": "1.7",
    "version": "1.0.0",
    "id": "{appid}"
}
```

The version is correctly replaced, but the appid isn't. Other times the appid is replaced, but other parameters aren't.

**Comment by karthigb** [comment]
Hi sschutten. A fix for this issue should be out shortly.

**Comment by asnow003** [comment]
This fix should be in the latest version of the extension.  Please let us know if you are still having issues.
