### ISSUE TITLE
.publish folder gets created at the wrong place

### ISSUE THREAD

**Issue by meum** [OfficeDev/microsoft-teams-app-quickstarts#16]
I'm trying the Microsoft Teams App extension for Visual Studio. Is this the right place to report bugs with it?

In a project created with "place solution and project in the same directory", the .publish folder gets created in a new subfolder with the name of the project. E.g. my project is at `c:\project\project.csproj`, the .publish folder ends up at `c:\project\project\.publish`

**Comment by karthigb** [comment]
It should be in the root directory of the project. Make sure you select that option when creating a new project.
