### ISSUE TITLE
Environment variables replacement in manifest json doesn't happen correctly 

### ISSUE THREAD

**Issue by bansalrachita** [OfficeDev/microsoft-teams-app-quickstarts#17]
When adding parameterized string {appclientid} to `webApplicationInfo.id` field in the temaple `manifest.json` inside .publish folder, it doesn't populate the `webApplicationInfo.resource` field correctly.

Trying to pass in the parameterized string manually like ` api://{baseUrl0}/{appclientid}` inside resource field also doesn't work.

**Template manifest.json**
```
{
  ...
  "webApplicationInfo": {
      "id": "{appclientid}",
      "resource": "api://{baseUrl0}/{appclientid}" // not providing this field also produces the same output as below.
    }
}
```

**Output manifest.json**
```
{
  ...
  "webApplicationInfo": {
       "id": "625ae2e7-df68-48d2-b538-50eeed288578",
       "resource": "api://a94f36a07347.ngrok.io/undefined"
   }
}
```

Also, the documentation for the `.publish` folder says that the `teamsappid` is a supported property - which should be updated to correctly point to `appid` instead.

**Comment by karthigb** [comment]
Hi Rachita,

Thank you for bringing this to our attention. Expect a fix shortly.

**Comment by asnow003** [comment]
The fix for this issue will be released in ver 1.0.6 of the extension.  Which will arrive in the next couple weeks.

**Comment by dannygar** [comment]
This bug hasn't been fixed in 1.0.6. It's still present.

**Comment by asnow003** [comment]
So sorry, this fix has slipped...let me reopen.  We are updating it when we release our new tools/samples for SSO.  Will reopen this issue...

**Comment by asnow003** [comment]
So far ETA for the version with the fix is at most the end of Nov

**Comment by asnow003** [comment]
this feature has been deprecated in the toolkit..it will be returning in the next version of App Studio which will be integrated with the toolkits
