### ISSUE TITLE
Unable to import devPreview Manifest Version

### ISSUE THREAD

**Issue by louishawkins** [OfficeDev/microsoft-teams-app-quickstarts#20]
I am unable to import a package using the Microsoft Teams Toolkit when the package has a manifest using the "devPreview" version:

```json
    "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
    "manifestVersion": "devPreview",
```

![Screen Shot 2020-08-03 at 6 46 54 PM](https://user-images.githubusercontent.com/4502787/89237787-b759c080-d5b9-11ea-9dff-d42cf3a2f093.png)

**Comment by asnow003** [comment]
I'm sorry we currently don't support devPreview editing....but this is coming soon.  Sorry about the inconvenience.
