### ISSUE TITLE
Localized json files not included in package

### ISSUE THREAD

**Issue by sschutten** [OfficeDev/microsoft-teams-app-quickstarts#22]
Localized json files specified in the `additionalLanguages` object of the `localizationInfo` object in the manifest are not included in the generated package file. I can confirm the json file is available at the specified location.

E.g. the following localizationInfo object should include the nl.json file in the package.

``` json
"localizationInfo": {
    "defaultLanguageTag": "en-us",
    "additionalLanguages": [
        {
            "languageTag": "nl",
            "file": "nl.json"
        }
    ]
}
```

**Comment by asnow003** [comment]
Thank you for the info....looks like this is a bug.  I will create a work item for this and make sure it gets fixed.

**Comment by asnow003** [comment]
This issue will be resolved in our October 2020 release.  Thank you for your patience.
