### ISSUE TITLE
Outline icon is not transparent

### ISSUE THREAD

**Issue by StevieBleeds** [OfficeDev/microsoft-teams-app-quickstarts#23]
I've been encountering an issue lately where my app package is failing to validate and is citing the outline icon as being the problem.

The outline icon (please see attached) is transparent as per the guidelines in the documentation and the tool did work when I compiled a Teams app some weeks ago. However, I have gone to build an updated package over the weekend and upon validation, was met with the _Outline icon is not transparent_ error.

![outline](https://user-images.githubusercontent.com/39305886/90978159-73683480-e543-11ea-9c4d-08404aef6be2.png)

Have I missed anything?

**Comment by greybax** [comment]
Hi @StevieBleeds, thank you for your question. I've tested your outlineIcon for this validation rule and noticed that alpha channel for this icon is setting up to 216 for some parts of this icon, but it should be 0 for whole icon. 

Also please notice sure that outline icon supports any range of gray colors, which means any colors of grey from 0-255 in rgb.

**Comment by StevieBleeds** [comment]
Thank you for your response Aleksander. Is this something that has changed recently at all?

**Comment by greybax** [comment]
Yes, these changes have been released a couple weeks ago
