### ISSUE TITLE
Generated manifest file in Development.zip truncated if any property contains special character

### ISSUE THREAD

**Issue by kimsey0** [OfficeDev/microsoft-teams-app-quickstarts#24]
**Reproduction steps:**
1. Open the Microsoft Teams Toolkit extension in Visual Studio Code.
1. Create a new Teams app with any settings using the extension. This generates a `.publish` folder containing `manifest.json`, `Development.env`, and `Development.zip`.
2. Open `manifest.json` and add `’` (right single quotation mark) or `æ` (Danish letter) to any property value, for example `short` under `name` or `description`.
3. Save the file and wait for the _Updated publishing package: Development_ notification.
4. Unzip `Development.zip` and open `manifest.json` from inside it.

**Expected result:**
The generated `manifest.json` should be a valid JSON file.

**Actual result:**
The generated `manifest.json` is missing a closing `}`.

**Comment by karthigb** [comment]
Acknowledged. Thank for you bringing this to our attention.

**Comment by asnow003** [comment]
Please expect a fix for this in our upcoming release in end of October 2020
