### ISSUE TITLE
Issue with launch.json

### ISSUE THREAD

**Issue by sandeepvootoori** [OfficeDev/microsoft-teams-app-quickstarts#30]
I am trying to debug an action based messaging extension through VSCode but its stopping at `Launching Teams to deploy app package`.
I don't see anything after that

**Comment by asnow003** [comment]
Sorry about the experience....we are changing the way we launch Teams via the launch.json in our next major release coming end of October 2020.  Please use the manual way to deploy your app as suggested in the readme.
