### ISSUE TITLE
No code is ever generated when the Workspace location is not on the C: Partition

### ISSUE THREAD

**Issue by brianwhited** [OfficeDev/microsoft-teams-app-quickstarts#35]
Using Microsoft Teams Toolkit v1.1.0 with Visual Studio Code On Window 10

Visual Studio Code Version

Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z (2 wks ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Windows 10 Version Information:
Edition: Windows 10 Pro
Version: 2004
OS Build: 19041.572
Experience: Windows Feature Experience Pack 120.2212.31.0

1. Select "Create a new Teams App"
2. Sign in
3. Choose "Bot" on the "Add Capabilities" screen.
4. Click Next
5.  Enter an Application Name
6. In the "Configure bot" area, choose "Use an existing bot registered with the Bot Framework"
7. Enter the bot's app ID  in the "Enter bot App ID" textbox
8. Enter the app password in the "Enter bot App Password" textbox.
9. Click the "Finish" button
10. Choose a folder location on an external USB Drive for the workspace and click the "Choose workspace folder" button
11. A popup is displayed with the message "Generating scaffold for TestProject", but no files are ever created.

I am using a USB 2.0 2TB Drive

**Comment by brianwhited** [comment]
If I select a workspace folder on my C drive, the files are created.

**Comment by bbprojectnet** [comment]
Same issue here. It's happend when you choose another than C partition. It doesn't have to be a USB drive.

**Comment by asnow003** [comment]
Found the issue...  there is a "slash" bug if you try to create at the root the code is adding an extra backslash.  To mitigate try selecting a sub folder or creating one and don't use the root drive until this bug is fixed

**Comment by brianwhited** [comment]
Unfortunately, I don’t mean at the root of c:. I mean that if you try to save the project in a drive other than the c drive,nothing ever happens. For example: c:\git\projectname works but d:\git\projectname does not work.

**Comment by asnow003** [comment]
@brianwhited thank you...I am also going to add better error messaging so it will show the error in a notification so we can debug why its not working in your case.  I think I should have that ready by Monday or Tuesday.

**Comment by brianwhited** [comment]
Thank you!

**Comment by asnow003** [comment]
@brianwhited I just pushed a new version 1.1.2.  Can you give it a try...I tested it saving to my C and D drive at the root and sub folders...would be great to see the error message with the path it will show if it fails.

**Comment by brianwhited** [comment]
It works now. Thank you!
