### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pm-MellingMedical** [OfficeDev/microsoft-teams-app-quickstarts#39]
- Issue Type: `Performance`
- Extension Name: `ms-teams-vscode-extension`
- Extension Version: `1.1.2`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\pmell\AppData\Local\Temp\TeamsDevApp.ms-teams-vscode-extension-unresponsive.cpuprofile.txt
[TeamsDevApp.ms-teams-vscode-extension-unresponsive.cpuprofile.txt](https://github.com/OfficeDev/microsoft-teams-app-quickstarts/files/5498303/TeamsDevApp.ms-teams-vscode-extension-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by karthigb** [comment]
This doesn't appear to be related to the extension
