### ISSUE TITLE
APP Studio in Teams toolkit extension always open latest App

### ISSUE THREAD

**Issue by SLdragon** [OfficeDev/microsoft-teams-app-quickstarts#42]
I am using latest teams toolkit extension, I found that App Studio in Teams toolkit extension always open latest App I created, even if I open an old project, it still show the latest one.

Repro steps:
1. Create a teams project, and open it in the App Studio in VSCode, we can name it first App
2. Create another teams project, and open it in the App Studio in VSCode, we can name it second App
3. Close all the project and VSCode
4. Open the first App in VSCode, and open the App Studio in VSCode
5. You would see the App Studio not show the first App but show the second App

**Comment by asnow003** [comment]
Let me check that out...looks like it is caching the id in the workspace instead of reading from the package.json

**Comment by asnow003** [comment]
Thanks for reporting this issue...I found it was a caching issue and I have made the fix.  This should be updated in our 1.1.3 version coming out next week.

**Comment by SLdragon** [comment]
Thank you @asnow003
