### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by fr34q** [OfficeDev/microsoft-teams-app-quickstarts#43]
It would be nice to create Teams app based on TypeScript and support it with the tool flow. (Sorry that the description is that short but I guess the title speaks for itself...)

**Comment by asnow003** [comment]
thank you for the feedback!  ...and YES TypeScript support is coming next year.  Within the first few months we hope but it is coming

**Comment by karthigb** [comment]
Closing as this is a feature request.

**Comment by Sangyaaak** [comment]
looking forward to have typescript supported too
