### ISSUE TITLE
Press f5 cannot install Teams App when using my own account

### ISSUE THREAD

**Issue by SLdragon** [OfficeDev/microsoft-teams-app-quickstarts#44]
Hi, I am using latest teams toolkit, when I create and install App on my Microsoft account, it works fine, however, when I am using my own office365 dev account, I cannot install the App through F5, it shows the errors as below, I already allowed user to install App in teams setting page:
![image](https://user-images.githubusercontent.com/5545529/99938259-61946880-2da2-11eb-9452-a7f9684a93dd.png)

I have another try and find that I can install it by download the zip file and upload it to the teams, and I cannot install it directly from App Studio.

Any settings need to update to support install App from App Studio and press F5?

**Comment by asnow003** [comment]
After updating that setting to allow installation of apps on your tenant it can take some time before its "updated".  Its not instant... can you give it a little time and try again.
