### ISSUE TITLE
Uninstall messaging app

### ISSUE THREAD

**Issue by ankitbko** [OfficeDev/microsoft-teams-app-quickstarts#45]
How do I uninstall messaging app which is only enabled for "message" context. Right clicking on message context does not give any option to uninstall.

**Comment by karthigb** [comment]
Closing as this isn't related to the Teams Toolkit. 

If you sideloaded the app, you can delete it from App Studio.

**Comment by ankitbko** [comment]
@karthigb Can't seem to uninstall the app from App Studio. There is no option to uninstall the app.

**Comment by asnow003** [comment]
Sorry I think he meant to remove from App Studio you can delete it...  If you want to remove from Teams you have to click on the three dots under the "Files" on the left bar.  It opens all your installed apps... then right click on the one you want to get rid of and click uninstall

**Comment by ankitbko** [comment]
@asnow003 for some reason it doesn't show my app there. I will reach out you directly and you can connect me with right person who can help me out. Thanks for the help.
