### ISSUE TITLE
Microsoft teams toolkit press F5 do not install app

### ISSUE THREAD

**Issue by SLdragon** [OfficeDev/microsoft-teams-app-quickstarts#6]
Hi, team, I am using Microsoft teams toolkit to develop and debug the teams apps,  when I press F5, it will start the teams, but the teams app is not installed, I need to manually install it.

Here is the command inside the debug window
```
C:\Users\rentu.FAREAST\AppData\Local/Microsoft/Teams/current/teams.exe --installAppPackage=C:\Users\rentu.FAREAST\Desktop\TeamsDevExt\Test2\Test2/.publish/Development.zip --inspect-brk=40420 
```

The project is the sample project which created by the toolkit.

**Comment by asnow003** [comment]
To install the app you need to be in "Developer Preview" of Teams do you have that selected yet

**Comment by SLdragon** [comment]
Hi, @asnow003 , I am using "Developer Preview" of Teams, however, it doesn't install the Apps, I record a GIF about this, you can download it and take a look (The version of the Teams is 1.3.00.13565:
![teams](https://user-images.githubusercontent.com/5545529/86423176-108eb580-bcd7-11ea-9bee-cf6cdc3a085f.gif)

**Comment by victorgarciaaprea** [comment]
this isn't working for me either... Teams is launched but no app installed... any way to look at the logs to find out if `--installAppPackage` is working?

**Comment by asnow003** [comment]
Sorry I just checked...we have a "ring" based rollout of features.  I turned on the feature in on our developer preview ring but it looks like it hasn't made it there yet.  It looks like it might be another week.

**Comment by SLdragon** [comment]
Thank you asnow003 for your information, is it related to the Teams and we need to wait for the update of it?

**Comment by asnow003** [comment]
Yes its Teams related sorry, it will be out very soon to developer preview....it should have been there by now but its delayed being pushed forward.

**Comment by SLdragon** [comment]
Thank you asnow003!
