### ISSUE TITLE
Debug teams apps in VSCode

### ISSUE THREAD

**Issue by SLdragon** [OfficeDev/microsoft-teams-app-quickstarts#7]
Hi, teams, can I directly debug it from VSCode? Because when I press F5, I found there is a command which contains ***--inspect-brk=40420***, and I am wonder if I can debug the teams apps directly inside VSCode.

```
C:\Users\rentu.FAREAST\AppData\Local/Microsoft/Teams/current/teams.exe --installAppPackage=C:\Users\rentu.FAREAST\Desktop\TeamsDevExt\Test2\Test2/.publish/Development.zip --inspect-brk=40420 
```

**Comment by asnow003** [comment]
Thank you for your message.  What version of the toolkit were you using?  
The pressing of the "Play" should allow you to install the app in Teams for you without doing the manual steps.  The debugging part is the same as you would do when debugging a react app.  So think of Teams as a browser hosting your react website.  

Also, be sure you are in "Developer Preview" mode in Teams.  This update to the readme was recent so hopefully you have that in your version of the app.

**Comment by SLdragon** [comment]
Hi, @asnow003 , I am using toolkit 0.96, 
I can debug the react webpage using the config below:
```
        {
            "name": "Launch Chrome",
            "request": "launch",
            "type": "chrome",
            "url": "https://localhost:8008/tab",
            "webRoot": "${workspaceFolder}/src",
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${webRoot}/*",
            }
        },
```
![image](https://user-images.githubusercontent.com/5545529/86424042-5ba9c800-bcd9-11ea-8e53-ef11a288e1d0.png)

However, when it has been installed inside teams,  the break point cannot be hit in the VSCode.

The config is as below:

```
        {
            "name": "Debug (Development)",
            "type": "node",
            "request": "launch",
            "stopOnEntry": false,
            "windows": {
                "preLaunchTask": "ensureTeamsQuitWindows",
                "runtimeExecutable": "${env:LOCALAPPDATA}/Microsoft/Teams/current/teams.exe",
                "runtimeArgs": [
                    "--installAppPackage=${workspaceRoot}/.publish/Development.zip"
                ]
            },
            "osx": {
                "preLaunchTask": "debugTeamsOSX"
            },
            "sourceMaps": true,
        }
```
![image](https://user-images.githubusercontent.com/5545529/86424982-dd9af080-bcdb-11ea-8cfc-9eef5d1e464a.png)

Do you have any ideas about how to config the launch file?

**Comment by asnow003** [comment]
Sorry for the late response...this is something we have as an open issue dealing with our Desktop client and Electron.  Our recommendation for debugging an app will be to use the web client.
