### ISSUE TITLE
Getting a 404 when trying to use Edit app package

### ISSUE THREAD

**Issue by victorgarciaaprea** [OfficeDev/microsoft-teams-app-quickstarts#8]
The title says it all...

![image](https://user-images.githubusercontent.com/2917688/86418550-d4dbf780-bca6-11ea-97b2-ff31ef08b48c.png)

Is this a known issue? I'm running v0.9.6 of the toolkit.

**Comment by asnow003** [comment]
Thanks for the bug report...I think this is our issue we are having with your auth token being expired.  Can you try and logout and login again to see if that resolves the issue?

**Comment by asnow003** [comment]
Bug has been created and is currently being worked on.  This should be fixed in our next version 1.0.2.  Please reopen if you still experience this after you get this version.  In the meantime to unblock due to token expiration please logout then log back in.
