### ISSUE TITLE
Share feedback link goes to questionnaire, not this issues page

### ISSUE THREAD

**Issue by aosolis** [OfficeDev/microsoft-teams-app-quickstarts#9]
![image](https://user-images.githubusercontent.com/767208/87097650-7e1c7380-c1fa-11ea-9514-ec1e1fb69b84.png)

I expected the link to go to the issues page. Instead it goes to the questionnaire here (https://forms.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRz4_I42h_rxMipBYjs_ZJpJURFkySjJNRU5BMEJUTTZZTkY1NVdaMzFOSC4u), which is not about the VS Code extension.

**Comment by asnow003** [comment]
Good idea I like moving this to the issue page instead!
Bug 1035890: [VSC] "Share Feedback" should go to the associated issue page
Bug 1035893: [VS] "Share Feedback" should go to the associated issue page
